# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: From ChromeDome to your dome.
email: robie1373@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lessons learned while trying to improve my own life. I fix tech, I break tech
  I build tech, I teach tech. Whatever it takes. InfoSec, coding, hacking, WebAppSec, 
  micro-electronics, ham radio, teaching. If it isn't here, I won't 
  remember it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robie1373.github.io" # the base hostname & protocol for your site
twitter_username: robie1373
github_username:  robie1373

# Build settings
markdown: kramdown
